vpc-id              = "vpc-0a744f2efc4febb2a"
key-name            = "snaatak.pem"
server-type         = "t2.micro"
subnet-id           = "subnet-009e342da70d1d460"
server-name         = "qa-openvpn-Server"
